spring.application.name=customer-service

server.port=8071

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true